Repository ublue-os/homebrew-tap, pull requests merged in 2025-09, with the labels that each got.

#35 feat: add aurora-wallpapers
  Casks/aurora-wallpapers.rb
  README.md
Labels: enhancement, size:S, lgtm

#39 feat: add dynamic bluefin wallpapers for KDE Plasma
  Casks/bluefin-wallpapers-plasma-dynamic.rb
  README.md
Labels: enhancement, size:S, lgtm

#43 chore: update formula sha
  Formula/asusctl.rb
  README.md
Labels: size:XS

#52 chore: visual-studio-code-linux 1.104.2
  Casks/visual-studio-code-linux.rb
Labels: size:XS, lgtm
